// Mechas (机械族) Lifeform tech catalog — draft skeleton.
// Data source: OGame community wiki (ogame.fandom.com/wiki/Lifeforms#Mechas) — web fetch blocked in env;
// shape & ID conventions follow community OGotcha-style naming (lf_mechas_*).
// TODO: verify cost/prereqs against live ogame 2026 (M6 audit will reconcile).
import type { LifeformTechCatalog, LifeformBuildingEntry, LifeformResearchEntry } from "./types.js";
import type { Resources } from "../types.js";

const pow = (base: number, k: number) => (l: number): Resources => ({
  m: Math.floor(base * Math.pow(k, l - 1)),
  c: Math.floor(base * 0.5 * Math.pow(k, l - 1)),
  d: 0,
  e: 0,
});
const powD = (base: number, k: number) => (l: number): Resources => ({
  m: Math.floor(base * Math.pow(k, l - 1)),
  c: Math.floor(base * 0.5 * Math.pow(k, l - 1)),
  d: Math.floor(base * 0.25 * Math.pow(k, l - 1)),
  e: 0,
});

const buildings: Record<string, LifeformBuildingEntry> = {
  assemblyLine: {
    id: "assemblyLine",
    display_name_zh: "裝配線",
    display_name_en: "Assembly Line",
    requires: {},
    cost_at: pow(8, 1.2),
    verified_against_live: false,
  },
  fusionCellFactory: {
    id: "fusionCellFactory",
    display_name_zh: "聚變電池工廠",
    display_name_en: "Fusion-Cell Factory",
    requires: { assemblyLine: 1 },
    cost_at: pow(7, 1.23),
    verified_against_live: false,
  },
  roboticsResearchCentre: {
    id: "roboticsResearchCentre",
    display_name_zh: "機器人研究中心",
    display_name_en: "Robotics Research Centre",
    requires: { assemblyLine: 1 },
    cost_at: pow(22_000, 1.4),
    verified_against_live: false,
  },
  updateNetwork: {
    id: "updateNetwork",
    display_name_zh: "更新網絡",
    display_name_en: "Update Network",
    requires: { roboticsResearchCentre: 2 },
    cost_at: pow(35_000, 1.4),
    verified_against_live: false,
  },
  quantumComputerCentre: {
    id: "quantumComputerCentre",
    display_name_zh: "量子計算中心",
    display_name_en: "Quantum Computer Centre",
    requires: { roboticsResearchCentre: 3 },
    cost_at: pow(50_000, 1.5),
    verified_against_live: false,
  },
  automatisedAssemblyCentre: {
    id: "automatisedAssemblyCentre",
    display_name_zh: "自動化裝配中心",
    display_name_en: "Automatised Assembly Centre",
    requires: { assemblyLine: 5 },
    cost_at: pow(60_000, 1.5),
    verified_against_live: false,
  },
  highPerformanceTransformer: {
    id: "highPerformanceTransformer",
    display_name_zh: "高性能變壓器",
    display_name_en: "High-Performance Transformer",
    requires: { fusionCellFactory: 3 },
    cost_at: pow(40_000, 1.4),
    verified_against_live: false,
  },
  microchipAssemblyLine: {
    id: "microchipAssemblyLine",
    display_name_zh: "微芯片裝配線",
    display_name_en: "Microchip Assembly Line",
    requires: { assemblyLine: 5, roboticsResearchCentre: 2 },
    cost_at: pow(75_000, 1.5),
    verified_against_live: false,
  },
  productionAssemblyHall: {
    id: "productionAssemblyHall",
    display_name_zh: "生產裝配廳",
    display_name_en: "Production Assembly Hall",
    requires: { automatisedAssemblyCentre: 3 },
    cost_at: pow(100_000, 1.5),
    verified_against_live: false,
  },
  highPerformanceSynthesiser: {
    id: "highPerformanceSynthesiser",
    display_name_zh: "高性能合成器",
    display_name_en: "High-Performance Synthesiser",
    requires: { microchipAssemblyLine: 3 },
    cost_at: powD(120_000, 1.5),
    verified_against_live: false,
  },
  chipMassProduction: {
    id: "chipMassProduction",
    display_name_zh: "芯片量產工廠",
    display_name_en: "Chip Mass Production",
    requires: { microchipAssemblyLine: 5 },
    cost_at: pow(160_000, 1.5),
    verified_against_live: false,
  },
  nanoRepairBotFactory: {
    id: "nanoRepairBotFactory",
    display_name_zh: "納米修復機器人工廠",
    display_name_en: "Nano Repair Bot Production",
    // v0.0.742 — operator "其他种族一样的依赖关系". Final-tier mirror of
    // kaelesh supraRefractor pattern: 4 tier-2 buildings at L5.
    requires: { highPerformanceSynthesiser: 5, productionAssemblyHall: 5, chipMassProduction: 5, quantumComputerCentre: 5 },
    cost_at: powD(220_000, 1.5),
    verified_against_live: false,
  },
};

const research: Record<string, LifeformResearchEntry> = {
  catalyserTechnology: {
    id: "catalyserTechnology",
    display_name_zh: "催化劑技術",
    display_name_en: "Catalyser Technology",
    requires: { roboticsResearchCentre: 1 },
    cost_at: pow(6_500, 2),
    verified_against_live: false,
  },
  plasmaDrive: {
    id: "plasmaDrive",
    display_name_zh: "等離子驅動",
    display_name_en: "Plasma Drive",
    requires: { roboticsResearchCentre: 1 },
    cost_at: pow(9_000, 2),
    verified_against_live: false,
  },
  efficiencyModule: {
    id: "efficiencyModule",
    display_name_zh: "效率模塊",
    display_name_en: "Efficiency Module",
    requires: { roboticsResearchCentre: 1 },
    cost_at: pow(7_000, 2),
    verified_against_live: false,
  },
  depotAI: {
    id: "depotAI",
    display_name_zh: "倉儲 AI",
    display_name_en: "Depot AI",
    requires: { roboticsResearchCentre: 2 },
    cost_at: pow(12_000, 2),
    verified_against_live: false,
  },
  generalOverhaulLightFighter: {
    id: "generalOverhaulLightFighter",
    display_name_zh: "輕型戰機大修",
    display_name_en: "General Overhaul: Light Fighter",
    requires: { roboticsResearchCentre: 2 },
    cost_at: pow(20_000, 2),
    verified_against_live: false,
  },
  automatedTransportLines: {
    id: "automatedTransportLines",
    display_name_zh: "自動化運輸線",
    display_name_en: "Automated Transport Lines",
    requires: { roboticsResearchCentre: 2 },
    cost_at: pow(15_000, 2),
    verified_against_live: false,
  },
  improvedDroneAI: {
    id: "improvedDroneAI",
    display_name_zh: "改進無人機 AI",
    display_name_en: "Improved Drone AI",
    requires: { roboticsResearchCentre: 3 },
    cost_at: pow(28_000, 2),
    verified_against_live: false,
  },
  experimentalRecyclingTechnology: {
    id: "experimentalRecyclingTechnology",
    display_name_zh: "實驗性回收技術",
    display_name_en: "Experimental Recycling Technology",
    requires: { roboticsResearchCentre: 3 },
    cost_at: pow(50_000, 2),
    verified_against_live: false,
  },
  generalOverhaulCruiser: {
    id: "generalOverhaulCruiser",
    display_name_zh: "巡洋艦大修",
    display_name_en: "General Overhaul: Cruiser",
    requires: { roboticsResearchCentre: 4 },
    cost_at: powD(80_000, 2),
    verified_against_live: false,
  },
  slingshotAutopilot: {
    id: "slingshotAutopilot",
    display_name_zh: "彈弓自動駕駛",
    display_name_en: "Slingshot Autopilot",
    requires: { roboticsResearchCentre: 4 },
    cost_at: powD(100_000, 2),
    verified_against_live: false,
  },
  highTemperatureSuperconductors: {
    id: "highTemperatureSuperconductors",
    display_name_zh: "高溫超導",
    display_name_en: "High-Temperature Superconductors",
    requires: { roboticsResearchCentre: 5 },
    cost_at: powD(150_000, 2),
    verified_against_live: false,
  },
  generalOverhaulBattleship: {
    id: "generalOverhaulBattleship",
    display_name_zh: "戰列艦大修",
    display_name_en: "General Overhaul: Battleship",
    requires: { roboticsResearchCentre: 5 },
    cost_at: powD(200_000, 2),
    verified_against_live: false,
  },
  // v0.0.666 — fill missing canonical 13213-13218.
  artificialSwarmIntelligence: {
    id: "artificialSwarmIntelligence",
    display_name_zh: "人工蜂群智能",
    display_name_en: "Artificial Swarm Intelligence",
    requires: { roboticsResearchCentre: 5 },
    cost_at: powD(180_000, 2),
    verified_against_live: false,
  },
  generalOverhaulBattlecruiser: {
    id: "generalOverhaulBattlecruiser",
    display_name_zh: "戰鬥巡洋艦大修",
    display_name_en: "General Overhaul: Battlecruiser",
    requires: { roboticsResearchCentre: 6 },
    cost_at: powD(250_000, 2),
    verified_against_live: false,
  },
  generalOverhaulBomber: {
    id: "generalOverhaulBomber",
    display_name_zh: "導彈艦大修",
    display_name_en: "General Overhaul: Bomber",
    requires: { roboticsResearchCentre: 6 },
    cost_at: powD(300_000, 2),
    verified_against_live: false,
  },
  generalOverhaulDestroyer: {
    id: "generalOverhaulDestroyer",
    display_name_zh: "毀滅者大修",
    display_name_en: "General Overhaul: Destroyer",
    requires: { roboticsResearchCentre: 6 },
    cost_at: powD(350_000, 2),
    verified_against_live: false,
  },
  experimentalWeaponsTechnology: {
    id: "experimentalWeaponsTechnology",
    display_name_zh: "實驗性武器技術",
    display_name_en: "Experimental Weapons Technology",
    requires: { roboticsResearchCentre: 7 },
    cost_at: powD(500_000, 2),
    verified_against_live: false,
  },
  mechanGeneralEnhancement: {
    id: "mechanGeneralEnhancement",
    display_name_zh: "機械族通用強化",
    display_name_en: "Mechan General Enhancement",
    requires: { roboticsResearchCentre: 7 },
    cost_at: powD(600_000, 2),
    verified_against_live: false,
  },
};

export default {
  species: "mechas",
  buildings,
  research,
} satisfies LifeformTechCatalog;
